from django.shortcuts import render
from djanggo.http import HttpResponse
from django.template.loader import get_template
from django.template import Context
from django import forms
from django.forms import ModelForm
from datalogger import models


# Create your views here.

# First some autogenerated forms from models
class SoilMoistMesureForm(ModelForm):
    class Meta:
        model = SoilMoistMesure
        fields = [ "plant", "time", "value"]

class TempForm(ModelForm):
    class Meta:
        model = TempHumMesure
        fields = ['time', 'temp', 'humi', 'plant']

   

class PlantForm(ModelForm):
    class Meta:
        model = Plant
        fields = [ 'espece', 'name' ]
        help_texts = {
            'name': "This field is optional, but can be helpful to a human to search for a particular plant. Otherwise primary indexes are used, and they are just numbers",

            }



class GeneralView(TemplateResponse):
    template = "base.html"


class InputView(GeneralView):
    template = form.html
    title = "Please Input New Mesurement"
    @Override
    def as_view(self, form):
        try: 
            form.is_bound()
        except:
            print "Not a form passed as argument, you fail, coder!"
 


        resp = render(template, { 'form': form, 'title': title }
        return HttpResponse(resp)



class 
